server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mySql://localhost:3306/demo4
    username: root
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  mail:
    host: smtp.gmail.com
    password: pgwi cmdo qjsn hjtr
    port: 587
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
    username: doanpy20031234@gmail.com
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1050501362620628
            client-secret: 225bb03830263921ae15aa7a1647a0d6
          google:
            client-id: 14152977969-lqid1rgojd63njtsd6sg6sv4iftjo8u5.apps.googleusercontent.com
            client-secret: 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
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
